pipeline {
  agent any

  environment {
    IMAGE_NAME = 'my-node-app'
    CONTAINER_PORT = '3000'
  }
  
    stage('Build') {
      agent {
        docker {
          image 'node:20-alpine'
          args '--user=root' // Ensures npm has correct permissions
        }
      }
      steps {
        sh 'npm install'
      }
    }

    stage('Test') {
      steps {
        sh 'npm test'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t ${IMAGE_NAME} .'
      }
    }

    stage('Run Container') {
      steps {
        sh 'docker run -d -p 3000:${CONTAINER_PORT} --name my-running-app ${IMAGE_NAME}'
      }
    }
  }

  post {
    success {
      echo 'Application deployed successfully!'
    }
    failure {
      echo 'Build failed. Check logs!'
    }
  }
}
