pipeline {
  agent none

  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.9.6-eclipse-temurin-17' }
      }
      steps {
        sh 'mvn --version'
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:20-alpine' }
      }
      steps {
        sh 'node --version'
        sh 'npm install'
        sh 'npm test'
      }
    }

    stage('Build Docker Image') {
      agent {
        docker { image 'docker:latest' }
      }
      steps {
        sh 'docker build -t my-node-app .'
      }
    }

    stage('Run Container') {
      agent {
        docker { image 'docker:latest' }
      }
      steps {
        sh 'docker run -d -p 3000:3000 --name my-running-app my-node-app'
      }
    }
  }

  post {
    success {
      echo 'Application deployed successfully!'
    }
    failure {
      echo 'Build failed. Check logs!'
    }
  }
}
